### ISSUE TITLE
bug: lib not working properly after npm install

### ISSUE THREAD

**Issue by ankurrsinghal** [svelte-legos/svelte-legos#21]

**Comment by snakeshift** [comment]
same

**Comment by ankurrsinghal** [comment]
@snakeshift fixed the errors, the utilities can now be imported!

**Comment by snakeshift** [comment]
@ankurrsinghal Thanks for the quick response!
I confirmed "textareaAutosizeAction" is working great.

I'm always use vueuse on my job and it would be great if this package would be the same standing.

**Comment by ankurrsinghal** [comment]
Cool, closing the issue :).
